apiVersion: v1
kind: Namespace
metadata:
  name: quay-enterprise
  annotations:
    openshift.io/node-selector: "node-role.kubernetes.io/infra="
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Exists", "effect":
      "NoSchedule", "key": "node-role.kubernetes.io/infra"},{"operator": "Exists","effect":
      "NoExecute", "key": "node-role.kubernetes.io/infra"} ]'
spec: {}
---
apiVersion: v1
data:
  config.yaml: QUxMT1dfUFVMTFNfV0lUSE9VVF9TVFJJQ1RfTE9HR0lORzogZmFsc2UKQVVUSEVOVElDQVRJT05fVFlQRTogTERBUApBVkFUQVJfS0lORDogbG9jYWwKREVGQVVMVF9UQUdfRVhQSVJBVElPTjogMncKRU5URVJQUklTRV9MT0dPX1VSTDogL3N0YXRpYy9pbWcvcXVheS1ob3Jpem9udGFsLWNvbG9yLnN2ZwpFWFRFUk5BTF9UTFNfVEVSTUlOQVRJT046IHRydWUKRkVBVFVSRV9BQ1RJT05fTE9HX1JPVEFUSU9OOiBmYWxzZQpGRUFUVVJFX0FOT05ZTU9VU19BQ0NFU1M6IGZhbHNlCkZFQVRVUkVfQVBQX1NQRUNJRklDX1RPS0VOUzogdHJ1ZQpGRUFUVVJFX0JJVEJVQ0tFVF9CVUlMRDogZmFsc2UKRkVBVFVSRV9CTEFDS0xJU1RFRF9FTUFJTFM6IGZhbHNlCkZFQVRVUkVfQlVJTERfU1VQUE9SVDogZmFsc2UKRkVBVFVSRV9DSEFOR0VfVEFHX0VYUElSQVRJT046IHRydWUKRkVBVFVSRV9ESVJFQ1RfTE9HSU46IHRydWUKRkVBVFVSRV9FWFRFTkRFRF9SRVBPU0lUT1JZX05BTUVTOiB0cnVlCkZFQVRVUkVfRklQUzogZmFsc2UKRkVBVFVSRV9HSVRIVUJfQlVJTEQ6IGZhbHNlCkZFQVRVUkVfR0lUSFVCX0xPR0lOOiBmYWxzZQpGRUFUVVJFX0dJVExBQl9CVUlMRDogZmFsc2UKRkVBVFVSRV9HT09HTEVfTE9HSU46IGZhbHNlCkZFQVRVUkVfSU5WSVRFX09OTFlfVVNFUl9DUkVBVElPTjogZmFsc2UKRkVBVFVSRV9NQUlMSU5HOiBmYWxzZQpGRUFUVVJFX05PTlNVUEVSVVNFUl9URUFNX1NZTkNJTkdfU0VUVVA6IGZhbHNlCkZFQVRVUkVfUEFSVElBTF9VU0VSX0FVVE9DT01QTEVURTogdHJ1ZQpGRUFUVVJFX1BST1hZX1NUT1JBR0U6IHRydWUKRkVBVFVSRV9TRUNVUklUWV9OT1RJRklDQVRJT05TOiB0cnVlCkZFQVRVUkVfVEVBTV9TWU5DSU5HOiB0cnVlCkZFQVRVUkVfVVNFUl9DUkVBVElPTjogdHJ1ZQpGRUFUVVJFX1VTRVJfTEFTVF9BQ0NFU1NFRDogdHJ1ZQpGRUFUVVJFX1VTRVJfTE9HX0FDQ0VTUzogZmFsc2UKRkVBVFVSRV9VU0VSX01FVEFEQVRBOiBmYWxzZQpGRUFUVVJFX1VTRVJfUkVOQU1FOiBmYWxzZQpGRUFUVVJFX1VTRVJOQU1FX0NPTkZJUk1BVElPTjogdHJ1ZQpGUkVTSF9MT0dJTl9USU1FT1VUOiAxMG0KR0lUSFVCX0xPR0lOX0NPTkZJRzoge30KR0lUSFVCX1RSSUdHRVJfQ09ORklHOiB7fQpHSVRMQUJfVFJJR0dFUl9LSU5EOiB7fQpMREFQX0FETUlOX0ROOiBjbj1mY0FEQmluZFVzZXJPQ1BQLG91PV9UZWNobmljYWwsb3U9QWNjb3VudHMsZGM9ZmMsZGM9ZGlyLGRjPWNydG5ldApMREFQX0FETUlOX1BBU1NXRDogc3FSZ2NzUXVucU1LcHVOCkxEQVBfQUxMT1dfSU5TRUNVUkVfRkFMTEJBQ0s6IGZhbHNlCkxEQVBfQkFTRV9ETjoKLSBkYz1mYwotIGRjPWRpcgotIGRjPWNydG5ldApMREFQX0VNQUlMX0FUVFI6IG1haWwKTERBUF9VSURfQVRUUjogc0FNQWNjb3VudE5hbWUKTERBUF9VUkk6IGxkYXBzOi8vbGRhcC5mYy5kaXIuY3J0bmV0OjYzNgpMREFQX1VTRVJfRklMVEVSOiAiKCYob2JqZWN0Q2xhc3M9dXNlcikobWVtYmVyT2Y6MS4yLjg0MC4xMTM1NTYuMS40LjE5NDE6PUNOPXF1YXktbG9naW4tZmlsdGVyLE9VPXF1YXkuaW8sT1U9azhzRnVuY3Rpb25zLE9VPUZ1bmN0aW9ucyxPVT1BY2NvdW50cyxEQz1mYyxEQz1kaXIsREM9Y3J0bmV0KSkiCkxEQVBfVVNFUl9SRE46Ci0gb3U9QWNjb3VudHMKU1VQRVJfVVNFUlM6CiAgLSBmYzAyMzYKICAtIGZjMDgxNgogIC0gZmMwOTI1CiAgLSBmY2VmNjkKICAtIGZjZWUzNQpMT0dTX01PREVMOiBkYXRhYmFzZQpMT0dTX01PREVMX0NPTkZJRzoge30KTUFJTF9ERUZBVUxUX1NFTkRFUjogcXVheS1vcGVuc2hpZnQtdHJlbnRvQGFsbGl0dWRlLml0Ck1BSUxfUE9SVDogMjUKTUFJTF9TRVJWRVI6IHNtdHAuY3J0bmV0Ck1BSUxfVVNFX0FVVEg6IGZhbHNlCk1BSUxfVVNFX1RMUzogZmFsc2UKUFJFRkVSUkVEX1VSTF9TQ0hFTUU6IGh0dHBzClJFR0lTVFJZX1RJVExFOiBRdWF5IEFsbGl0dWRlClJFR0lTVFJZX1RJVExFX1NIT1JUOiBRdWF5ClNFQVJDSF9NQVhfUkVTVUxUX1BBR0VfQ09VTlQ6IDEwClNFQVJDSF9SRVNVTFRTX1BFUl9QQUdFOiAxMApTRVJWRVJfSE9TVE5BTUU6IHJlZ2lzdHJ5LXF1YXkuYXBwcy5mY2FrZ3QwMS5nZXN0aW9uZS5lbmV0ClNFVFVQX0NPTVBMRVRFOiB0cnVlClRBR19FWFBJUkFUSU9OX09QVElPTlM6Ci0gMncKVEVBTV9SRVNZTkNfU1RBTEVfVElNRTogNjBtClRFU1RJTkc6IGZhbHNlClVTRVJfUkVDT1ZFUllfVE9LRU5fTElGRVRJTUU6IDMwbQo=
kind: Secret
metadata:
  labels:
    app: quay-enterprise
    kind: registry
  name: quay-bootstrap-config
  namespace: quay-enterprise
type: Opaque
---
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: quay-bootstrap-config
  components:
    - kind: quay
      managed: true
    - kind: postgres
      managed: true
    - kind: clair
      managed: true
    - kind: redis
      managed: true
    - kind: horizontalpodautoscaler
      managed: true
    - kind: objectstorage
      managed: true
    - kind: route
      managed: true
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: false
    - kind: tls
      managed: true
    - kind: clairpostgres
      managed: true 
  

