apiVersion: v1
data:
  ca-bundle.crt: |
    <REDACTED>
kind: ConfigMap
metadata:
  name: user-ca-bundle
  namespace: openshift-config
---
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  name: cluster
spec:
  trustedCA:
    name: user-ca-bundle
