apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/external-secrets-operator.openshift-operators: ''
  name: external-secrets-operator
  namespace: external-secrets
spec:
  channel: stable
  name: external-secrets-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: ClusterExternalSecret.v1beta1.external-secrets.io,ClusterSecretStore.v1alpha1.external-secrets.io,ClusterSecretStore.v1beta1.external-secrets.io,ExternalSecret.v1alpha1.external-secrets.io,ExternalSecret.v1beta1.external-secrets.io,OperatorConfig.v1alpha1.operator.external-secrets.io,SecretStore.v1alpha1.external-secrets.io,SecretStore.v1beta1.external-secrets.io
  name: external-secrets
  namespace: external-secrets
spec:
  targetNamespaces:
  - external-secrets

 
