apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: logging-forwarder-config-gestione-tn-01 
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      name: "local-cluster"
  remediationAction: enforce
policies:
  - name: logging-forwarder-config-gestione-tn-01
    manifests:
      - path: logging-forwarder.yaml

