apiVersion: v1
kind: Secret
metadata:
  name: ldap-secret
  namespace: openshift-config
type: Opaque
data:
  bindPassword: "WU9VIEFSRSBBIEhBQ0tFUnZpcnQtbWFuYWdlciBXRUxMIERPTkUhCg=="
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - <REDACTED>
---
apiVersion: v1
data:
  ca.crt: <REDACTED>
kind: ConfigMap
metadata:
  name: ca-config-map
  namespace: openshift-config
