apiVersion: v1
data:
  password: <REDACTED>
  username: <REDACTED>
kind: Secret
metadata:
  name: ldap-group-sync
  namespace: group-sync-operator
type: Opaque
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: ldap-groupsync
  namespace: group-sync-operator
spec:
  providers:
  - ldap:
      augmentedActiveDirectory:
        groupMembershipAttributes:
        #Add filters here
        #- 'memberOf:1.2.840.113556.1.4.1941:'
        groupNameAttributes:
        - cn
        groupUIDAttribute: distinguishedName
        groupsQuery:
          baseDN: <REDACTED>
          derefAliases: never
          filter: <REDACTED>
          scope: sub
        userNameAttributes:
        - sAMAccountName
        usersQuery:
          baseDN: <REDACTED>
          derefAliases: never
          filter: (objectclass=person)
          pageSize: 0
          scope: sub
      caSecret:
        key: ca.crt
        kind: Secret
        name: ldap-ca
        namespace: group-sync-operator
      credentialsSecret:
        kind: Secret
        name: ldap-group-sync
        namespace: group-sync-operator
      insecure: false
      prune: true
      url: <REDACTED>
      whitelist:
      - <REDACTED>
    name: ldap
  schedule: '*/3 * * * *'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  generateName: cluster-admin-
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: <REDACTED>
