apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: groups-sync-config-gestione-tn-01
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      name: "local-cluster"
  remediationAction: enforce
policies:
  - name: groups-sync-config-gestione-tn-01
    manifests:
      - path: groups-sync-config.yaml 

