apiVersion: v1
kind: Namespace
metadata:
  name: group-sync-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/group-sync-operator.group-sync-operator: ""
  name: group-sync-operator
  namespace: group-sync-operator
spec:
  channel: alpha
  name: group-sync-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: group-sync-operator.v0.0.20
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: GroupSync.v1alpha1.redhatcop.redhat.io
  name: group-sync-operator
  namespace: group-sync-operator
spec:
  targetNamespaces:
  - group-sync-operator

