apiVersion: v1
data:
  tls.crt: <REDACTED>
  tls.key: <REDACTED>
kind: Secret
metadata:
  creationTimestamp: null
  name: api-cert
  namespace: openshift-config
type: kubernetes.io/tls
---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
    - names:
      - <REDACTED>
      servingCertificate:
        name: api-cert

